name: Deploy Web application

on:
  push:
    paths:
    - 'pubspec.yaml'

  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ—ï¸ Build application image (arm64v8)
        uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 4096
          base_image: raspios_lite_arm64:latest
          optimize_image: yes
          commands: |
              docker build . --file ./deploy/Dockerfile --tag zsdima/web-app-update:latest
              echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin
              docker push zsdima/web-app-update:latest

      #- name: ğŸ—ï¸ Build application image
      #  run: docker build . --file ./deploy/Dockerfile --tag zsdima/web-app-update:latest

      #- name: âœ¨ Log into registry
      #  run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

      #- name: ğŸ’¾ Push images to the Docker registry
      #  run: docker push zsdima/web-app-update:latest
