name: Deploy application container (amd64)

on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ğŸ—ï¸ Build application image
        run: docker build . --file ./deploy/Dockerfile --tag zsdima/web-app-update:latest

      - name: âœ¨ Log into registry
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

      - name: ğŸ’¾ Push images to the Docker registry
        run: docker push zsdima/web-app-update:latest
